on: [status]
jobs:
  circleci_artifacts_redirector_job:
    if: "${{ startsWith(github.event.context, 'ci/circleci: build') }}"
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: scientific-python/circleci-artifacts-redirector-action@7eafdb60666f57706a5525a2f5eb76224dc8779b  # v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.CIRCLECI_TOKEN }}
          artifact-path: 0/html/index.html
          circleci-jobs: build
          job-title: Check the rendered docs here!
